---
- name: Install Shibboleth Debian repository
  when: >
    ansible_os_family == 'Debian' and shibboleth_nginx_module_install | bool
  block:
    - name: Install Shibboleth Nginx repository signing key
      ansible.builtin.get_url:
        url: https://elan-ev.github.io/shibboleth-nginx-repo/gpgkey.asc
        dest: /etc/apt/trusted.gpg.d/nginx-mod-shibboleth.asc
        checksum: sha256:0e7cfae843aaa8166ec72eb3afafb126507f1743581431bf6e438af6edf75bb7
        owner: root
        group: root
        mode: '0644'

    - name: Install Shibboleth repository for Debian
      ansible.builtin.apt_repository:
        repo: >
          deb https://elan-ev.github.io/shibboleth-nginx-repo/{{ ansible_distribution | lower }}/{{ ansible_distribution_release }}
          {{ ansible_distribution_release }} {{ 'multiverse' if ansible_distribution.endswith('buntu') else 'non-free' }}
        filename: nginx-mod-shibboleth

- name: Install Shibboleth RPM repository
  when: ansible_os_family == 'RedHat'
  block:
    - name: Install Shibboleth repository for EL8
      ansible.builtin.yum_repository:
        file: shibboleth
        name: shibboleth
        description: Shibboleth (RedHat 8)
        mirrorlist: https://shibboleth.net/cgi-bin/mirrorlist.cgi/CentOS_8
        enabled: true
        gpgcheck: true
        gpgkey:
          - https://shibboleth.net/downloads/service-provider/RPMS/repomd.xml.key
          - https://shibboleth.net/downloads/service-provider/RPMS/cantor.repomd.xml.key
      when: >
        ansible_distribution_major_version == "8"

    - name: Install Shibboleth repository for EL9
      ansible.builtin.yum_repository:
        file: shibboleth
        name: shibboleth
        description: Shibboleth (rockylinux9)
        mirrorlist: https://shibboleth.net/cgi-bin/mirrorlist.cgi/rockylinux9
        enabled: true
        gpgcheck: true
        gpgkey:
          - https://shibboleth.net/downloads/service-provider/RPMS/repomd.xml.key
          - https://shibboleth.net/downloads/service-provider/RPMS/cantor.repomd.xml.key
      when: >
        ansible_distribution_major_version == "9"

    - name: Install Shibboleth Nginx repository
      ansible.builtin.yum_repository:
        file: shibboleth-nginx
        name: shibboleth-nginx
        description: Shibboleth Nginx packages - RHEL$releasever
        baseurl: https://elan-ev.github.io/shibboleth-nginx-repo/rhel/$releasever/
        enabled: true
        gpgcheck: true
        gpgkey:
          - https://elan-ev.github.io/shibboleth-nginx-repo/gpgkey.asc
      when: >
        shibboleth_fastcgi_support_enable | bool
        or shibboleth_nginx_module_install | bool

    - name: Install EPEL repository
      ansible.builtin.package:
        name: epel-release
