---
- name: Include repositories instalaltion tasks
  ansible.builtin.import_tasks: install_repository.yml

- name: Install Shibboleth on Debiban
  when: ansible_os_family == 'Debian'
  ansible.builtin.package:
    name:
      - shibboleth-sp-common
      - shibboleth-sp-utils
  notify: Restart shibboleth

- name: Install Shibboleth on EL
  when: ansible_os_family == 'RedHat'
  ansible.builtin.package:
    name: "{{ 'shibboleth-fastcgi' if shibboleth_fastcgi_support_enable | bool or shibboleth_nginx_module_install | bool else 'shibboleth' }}"
  notify: Restart shibboleth

- name: Enable Shibboleth daemon
  ansible.builtin.systemd:
    name: shibd
    enabled: true

- name: Include tasks if Nginx should be used
  when: shibboleth_fastcgi_support_enable | bool or shibboleth_nginx_module_install | bool
  block:
    - name: Install socket Systemd services
      ansible.builtin.template:
        src: "{{ item }}"
        dest: /etc/systemd/system/
        owner: root
        group: root
        mode: '0644'
      loop:
        - shibauthorizer.service
        - shibauthorizer.socket
        - shibresponder.service
        - shibresponder.socket
      register: systemd_unit_files_installed
      notify: Restart shibboleth sockets

    - name: Reload Systemd   # noqa no-handler
      ansible.builtin.systemd:
        daemon_reload: true
      when: systemd_unit_files_installed is changed

    - name: Enable Shibboleth daemon and socket units
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: true
      loop:
        - shibauthorizer.service
        - shibauthorizer.socket
        - shibresponder.service
        - shibresponder.socket

- name: Install Nginx Shibboleth module on Debian
  when: shibboleth_nginx_module_install | bool and ansible_os_family == 'Debian'
  ansible.builtin.package:
    name:
      - libnginx-mod-http-shibboleth
      - libnginx-mod-http-headers-more-filter
  notify: Reload nginx

- name: Install Nginx Shibboleth module on EL
  when: shibboleth_nginx_module_install | bool and ansible_os_family == 'RedHat'
  ansible.builtin.package:
    name:
      - nginx-mod-http-shibboleth
      - nginx-mod-http-headers-more-filter
  notify: Reload nginx
