---
- name: Restart shibboleth
  ansible.builtin.systemd:
    name: shibd
    state: restarted

- name: Restart shibboleth sockets
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
  loop:
    - shibauthorizer.socket
    - shibauthorizer.service
    - shibresponder.socket
    - shibresponder.service

- name: Reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
