---
driver:
  name: containers
dependency:
  name: galaxy
  enabled: false
platforms:
  - name: el8
    image: quay.io/rockylinux/rockylinux:8
    pre_build_image: false
    command: /sbin/init
    tmpfs:
      "/tmp": "exec"
      "/run": "rw,noexec,nosuid,nodev"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: el9
    image: quay.io/centos/centos:stream9
    pre_build_image: false
    command: /sbin/init
    tmpfs:
      "/tmp": "exec"
      "/run": "rw,noexec,nosuid,nodev"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: debian
    image: docker.io/debian:stable
    pre_build_image: false
    command: /sbin/init
    tmpfs:
      "/tmp": "exec"
      "/run": "rw,noexec,nosuid,nodev"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: ubuntu
    image: docker.io/ubuntu:latest
    pre_build_image: false
    command: /sbin/init
    tmpfs:
      "/tmp": "exec"
      "/run": "rw,noexec,nosuid,nodev"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
lint: |
  set -e
  yamllint -c .yamllint .
  ansible-lint
provisioner:
  name: ansible
verifier:
  name: ansible
